./stock-mapping_var1.sh DEU DE_BE 33
./stock-mapping_var1.sh DEU DE_BR 33
./stock-mapping_var1.sh DEU DE_BW 33
./stock-mapping_var1.sh DEU DE_BY 33
./stock-mapping_var1.sh DEU DE_HB 33
./stock-mapping_var1.sh DEU DE_HE 33
./stock-mapping_var1.sh DEU DE_HH 33
./stock-mapping_var1.sh DEU DE_MV 33
./stock-mapping_var1.sh DEU DE_NI 33
./stock-mapping_var1.sh DEU DE_NW 33
./stock-mapping_var1.sh DEU DE_RP 33
./stock-mapping_var1.sh DEU DE_SH 33
./stock-mapping_var1.sh DEU DE_SL 33
./stock-mapping_var1.sh DEU DE_SN 33
./stock-mapping_var1.sh DEU DE_ST 33
./stock-mapping_var1.sh DEU DE_TH 33
