$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_AL 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_CT 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_HI 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_KS 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_ME 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_MT 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_NJ 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_OK 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_SD 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_VT 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_AR 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_DC 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_IA 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_KY 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_MI 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_NC 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_NM 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_OR 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_TN 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_WA 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_AZ 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_DE 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_ID 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_LA 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_MN 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_ND 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_NV 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_PA 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_TX 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_WI 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_CA 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_FL 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_IL 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_MA 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_MO 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_NE 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_NY 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_RI 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_UT 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_WV 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_CO 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_GA 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_IN 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_MD 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_MS 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_NH 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_OH 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_SC 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_VA 56
$HOME/mat_stocks/stock-mapping/stock-mapping_var2.sh USA US_WY 56
