stock-mapping_var1.sh AUT AT_BU 35
stock-mapping_var1.sh AUT AT_KA 35
stock-mapping_var1.sh AUT AT_NO 35
stock-mapping_var1.sh AUT AT_OO 35
stock-mapping_var1.sh AUT AT_ST 35
stock-mapping_var1.sh AUT AT_SZ 35
stock-mapping_var1.sh AUT AT_TR 35
stock-mapping_var1.sh AUT AT_VO 35
stock-mapping_var1.sh AUT AT_WI 35
